version: "3"

services:
  frontend:
    build: 
      context: ./frontend
      target: dev
    depends_on:
      - backend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/src
      - /src/node_modules
    environment:
      API_URL: http://localhost:8081/
            
  backend:
    build: 
      context: ./backend
      target: dev
    ports:
      - 8081:8081
    volumes:
      - ./backend:/src
      - /src/node_modules
    depends_on: 
      - db
    environment:
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      SECRET: ${SECRET}
    
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}