version: "3"

services:
  frontend:
    build: 
      context: ./frontend
      args:
          - VUE_APP_API_URL=${API_URL}
    depends_on:
      - backend
    ports:
      - 8080:80
    volumes:
      - ./frontend:/src
      - /src/node_modules
            
  backend:
    build: 
      context: ./backend
    ports:
      - 8081:8081
    volumes:
      - ./backend:/src
      - /src/node_modules
    depends_on: 
      - db
    environment:
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      SECRET: ${SECRET}
      SIGNUP_ENABLE: ${SIGNUP_ENABLE}
    
  db:
    image: postgres
    volumes:
      - /home/vagrant/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}